version: "3.3"
services:
  service-auth-db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: actix
      POSTGRES_USER: actix
      POSTGRES_DB: auth
    volumes: ["pgdata:/var/lib/postgresql/data"]
    ports:
      - 5460:5432
  service-auth-restful:
    container_name: service-auth-restful
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - service-auth-db
    links:
      - service-auth-db

networks:
  default:
    external:
      name: service-auth

volumes:
  pgdata:
